services:

    onedev-server-backup:
        build:
            context: .
            dockerfile: dockerfile.onedev-server
        image: onedev-server:latest
        container_name: individual-studio-onedev-server-backup
        entrypoint: tar
        command:
            - -zcf
            - /root/backup/onedev-server-backup.tar.gz
            - -C/opt/onedev/
            - conf
            - site
        volumes:
            - onedev-server:/opt/onedev
            - onedev-backup:/root/backup
        profiles:
            - backup
        networks:
            - onedev

    onedev-server-restore:
        build:
            context: .
            dockerfile: dockerfile.onedev-server
        image: onedev-server:latest
        container_name: individual-studio-onedev-server-restore
        entrypoint: tar
        command:
            - -zxf
            - /root/backup/onedev-server-backup.tar.gz
            - -C/opt/onedev/
        volumes:
            - onedev-server:/opt/onedev
            - onedev-backup:/root/backup
        profiles:
            - restore
        networks:
            - onedev

    onedev-database-backup:
        build:
            context: .
            dockerfile: dockerfile.onedev-server
        image: onedev-server:latest
        container_name: individual-studio-onedev-database-backup
        entrypoint: /opt/onedev/bin/backup-db.sh
        command: /root/backup/onedev-database-backup.zip
        links:
            - onedev-server
        volumes:
            - onedev-server:/opt/onedev
            - onedev-backup:/root/backup
        profiles:
            - backup
        depends_on:
            - onedev-server
            - onedev-database
        networks:
            - onedev

    onedev-database-restore:
        build:
            context: .
            dockerfile: dockerfile.onedev-server
        image: onedev-server:latest
        container_name: individual-studio-onedev-database-restore
        entrypoint: /opt/onedev/bin/restore-db.sh
        command: /root/backup/onedev-database-backup.zip
        volumes:
            - onedev-server:/opt/onedev
            - onedev-backup:/root/backup
        profiles:
            - restore
        depends_on:
            - onedev-database
        networks:
            - onedev

networks:
    onedev:
        name: individual-studio-onedev

volumes:
    onedev-server:
        name: individual-studio-onedev-server

    onedev-backup:
        name: individual-studio-onedev-backup
